In [9]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.18.0


In [10]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [11]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [12]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.07096477, -0.7463218 , -0.36855674,  0.3284693 , -0.2513309 ,
        -0.20226899, -0.28670108, -0.08032216, -0.7645417 , -0.26939973]],
      dtype=float32)

In [13]:
tf.nn.softmax(predictions).numpy()

array([[0.13211536, 0.0583459 , 0.08512783, 0.17091733, 0.09571545,
        0.10052854, 0.09238915, 0.11356651, 0.05729247, 0.09400152]],
      dtype=float32)

In [14]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [15]:
loss_fn(y_train[:1], predictions).numpy()

2.2973135

In [16]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [17]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.8631 - loss: 0.4729
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.9545 - loss: 0.1544
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.9659 - loss: 0.1134
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.9733 - loss: 0.0888
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.9776 - loss: 0.0716


In [18]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - 1ms/step - accuracy: 0.9771 - loss: 0.0749


[0.07490251213312149, 0.9771000146865845]

In [19]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [20]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.9438497e-08, 9.0229255e-09, 2.1373085e-06, 1.6416081e-04,
        1.2749397e-10, 2.8204846e-07, 3.7474795e-13, 9.9983156e-01,
        3.2733959e-07, 1.4519588e-06],
       [2.6540270e-08, 5.7912956e-05, 9.9977344e-01, 1.6649142e-04,
        6.4660670e-15, 1.8200619e-06, 9.5477981e-10, 7.0701664e-14,
        3.1935880e-07, 1.9047231e-12],
       [1.0288350e-06, 9.9937576e-01, 8.3803323e-05, 4.0793329e-06,
        1.2888328e-05, 5.9775089e-06, 1.0649250e-04, 3.5056352e-04,
        5.9232396e-05, 2.8964325e-07],
       [9.9944383e-01, 2.2935764e-09, 3.5804017e-06, 2.6821479e-07,
        2.2130456e-07, 5.5561391e-06, 5.3881994e-04, 4.0234349e-06,
        1.6362675e-06, 1.8990487e-06],
       [3.0751533e-05, 3.3261816e-09, 1.3129310e-06, 3.4643236e-07,
        9.6464980e-01, 6.5505897e-06, 4.6355872e-05, 2.1968280e-04,
        6.0970115e-06, 3.5039101e-02]], dtype=float32)>